services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MSSQL_Server
    restart: always
    environment:
      SA_PASSWORD: "Tecnm123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./PuntoDeVentaTBD.sql:/var/opt/mssql/temp/PuntoDeVentaTBD.sql
    ports:
      - "1434:1433"
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 60 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P 'Tecnm123!' -No -I -i /var/opt/mssql/temp/PuntoDeVentaTBD.sql &&
      wait"

  backend:
    build: ./backend
    container_name: pos-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mssql

volumes:
  mssql-data: