services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MSSQL_Server
    restart: always
    environment:
      SA_PASSWORD: "Tecnm123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./PuntoDeVentaTBD.sql:/var/opt/mssql/temp/PuntoDeVentaTBD.sql
      - ./init/entrypoint.sh:/var/opt/mssql/entrypoint.sh
    ports:
      - "1434:1433"

  backend:
    build: ./backend
    container_name: pos-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - mssql

volumes:
  mssql-data: